version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/ReactiveUI.AndroidSupport"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Splat
    versions:
    - 9.0.5
